steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gsutil'
  args: ['-m', 'cp', 'index.html', 'styles.css', 'app.js', 'gs://${_BUCKET_NAME}/']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gsutil'
  args: ['-m', 'iam', 'ch', 'allUsers:objectViewer', 'gs://${_BUCKET_NAME}/*.js', 'gs://${_BUCKET_NAME}/*.html', 'gs://${_BUCKET_NAME}/*.css']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gsutil'
  args: ['web', 'set', '-m', 'index.html', 'gs://${_BUCKET_NAME}/']

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _BUCKET_NAME: autobj1

serviceAccount: 'projects/blissful-axiom-449912-a8/serviceAccounts/customservice@blissful-axiom-449912-a8.iam.gserviceaccount.com'